### ISSUE TITLE
Can't Support Chinese

### ISSUE THREAD

**Issue by randyh0329** [karan/slack-overflow#2]
` /overflow 中文 ` is not working

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

Screen Shot
![screen shot 2015-05-19 at 7 14 46 pm](https://cloud.githubusercontent.com/assets/6405893/7701598/61c971b4-fe5b-11e4-96cc-e5aeba0bce70.png)

**Comment by karan** [comment]
SO is in English. So I'm not really sure why you are searching for Chinese characters.

I'm making it fail elegantly instead now. https://github.com/karan/slack-overflow/commit/57f49d4375d87f5af5a2d405e3ef09ba1e94dbb3
